# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  # Use the following base box: https://vagrantcloud.com/box-cutter/ubuntu1404-docker
  config.vm.box = "box-cutter/ubuntu1404-docker"

  # Provision the software we need
  config.vm.provision "shell", path: "provision/java.sh"
  config.vm.provision "shell", path: "provision/maven.sh"
  config.vm.provision "shell", path: "provision/nginx.sh"

  # Clone code from github repo and run Docker instances
  config.vm.provision "shell", path: "provision/cloneRepoAndBuild.sh"
  config.vm.provision "shell", path: "provision/setupDockerInstances.sh"
  config.vm.provision "shell", run: "always", path: "provision/runStuff.sh"
  config.vm.provision "shell", run: "always", path: "provision/warmup.sh"

end
